### ISSUE TITLE
Still has use despite native implementation

### ISSUE THREAD

**Issue by SheepCommander** [lavgup/image-to-clipboard#3]
There are some images where discord does not by default allow you to copy the image (only the URL) however this plugin still allows you to copy those images and it works.

My actual request: **Could you set exceptions so the option only shows up when discord does not already natively allow you to copy the image?**

OR if that is not possible/too hard, completely replacing the built-in Copy Image also works

**Comment by lavgup** [comment]
Resolved with https://github.com/lavgup/image-to-clipboard/commit/8a96dcf9c91d3c7b1309f6d47e1f72b48561c636

**Comment by SheepCommander** [comment]
YOOOOO I wasn't sure if you actually still maintained this, thanks so much this is amazing <3
